version: '3.8'

services:
  backend:
    build: ./backend
    container_name: task-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/database:/app/database
    restart: always

  frontend:
    build: ./frontend
    container_name: task-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
